[[headlines]]
title = "Client update 4.0.3"
date = "2022-03-10T14:30:00"
content = """
Updated the client to make configuration simpler. The individual server settings have been removed in favor of just one address setting.

Pickup the latest version [here](https://github.com/SkunkWorks-Studio/HamperTown/releases/latest).

In other news, the March game update has been released. Will be looking at providing the new game patch and compiling server updates in the near future.
"""

[[headlines]]
title = "FFXI Version Update"
date = "2022-03-02T22:03:00"
content = """
The FFXI game files have been updated to version `30220204_0`. We now have access to the next 4 wardrobe storage options as well as a whole host of new features and implemented functionality as a result of moving to the new server backend.

See [LandSandBoat](https://github.com/LandSandBoat/server) for more details on the server implementation.
"""
