[[headlines]]
title = "FFXI Version Update"
date = "2022-04-02T22:03:00"
content = """
The FFXI game files have been updated to version 30220204\_0. We now have access to the next 4 wardrobe storage options as well as a whole host of new features and implemented functionality as a result of moving to the new server backend.

See [LandSandBoat](https://github.com/LandSandBoat/server) for more details on the server implementation.
"""

[[headlines]]
title = "Client News Feed Update"
date = "2022-03-02T19:43:00"
content = """
Implemented getting the news feed from GitHub replacing the dummy lorem ipsum placeholders.

Please get the latest version [here](https://github.com/SkunkWorks-Studio/HamperTown/releases/latest).
"""

[[headlines]]
title = "Client Connectivity Patch"
date = "2022-03-01T20:11:00"
content = """
Patched the client to connect to the server from an external source.

Please get the latest version [here](https://github.com/SkunkWorks-Studio/HamperTown/releases/latest).
"""

[[headlines]]
title = "Initial Release"
date = "2022-03-01T19:48:00"
content = """
Initial release of the new client written in Rust moving away from the bloat of an Electron application.
"""
