[[headlines]]
title = "Client update 4.1.2"
date = "2022-04-21T15:22:00"
content = """
- New patch was generated and small adjustment added to the call to launch the game.

Let me know if you run across any issues.

Pickup the latest version [here](https://github.com/SkunkWorks-Studio/HamperTown/releases/latest).
"""

[[headlines]]
title = "Client update 4.1.0"
date = "2022-03-11T07:03:00"
content = """
- Fixed patching bug that was preventing a fresh install from updating properly.
- Added the client version number to the footer

Pickup the latest version [here](https://github.com/SkunkWorks-Studio/HamperTown/releases/latest).
"""

[[headlines]]
title = "Client update 4.0.3"
date = "2022-03-10T14:30:00"
content = """
Updated the client to make configuration simpler. The individual server settings have been removed in favor of just one address setting.

Pickup the latest version [here](https://github.com/SkunkWorks-Studio/HamperTown/releases/latest).
"""

[[headlines]]
title = "FFXI Version Update"
date = "2022-03-02T22:03:00"
content = """
The FFXI game files have been updated to version `30220204_0`. We now have access to the next 4 wardrobe storage options as well as a whole host of new features and implemented functionality as a result of moving to the new server backend.

See [LandSandBoat](https://github.com/LandSandBoat/server) for more details on the server implementation.
"""
